### ISSUE TITLE
Logs are not writing when using node-for-log4j v2.0.2 in ACE V11.0.0.24 on Windows 11

### ISSUE THREAD

**Issue by vietph83** [ot4i/node-for-log4j#9]
Hi support team

I download the following files from https://github.com/ot4i/node-for-log4j/releases/tag/v2.0.2
+ Log4jLoggingNode_v2.0.1.par
+ Log4jLoggingPluginFeature_v2.0.2.zip

=> I copy Log4jLoggingNode_v2.0.1.par to C:\Program Files\IBM\ACE\11.0.0.24\server\jplugin

=> I install the Log4jLoggingPluginFeature_v2.0.2.zip to ACE V11.0.0.0.24 Toolkit

=> I develop the simple TEST FLOW using the Log4jLoggingPlugin node

![image](https://github.com/ot4i/node-for-log4j/assets/13336339/638141d8-8a9e-45b1-a3e2-13a68199a40d)
+ I set Input directory = C:/temp/log4j_input for the FileInput node
+ I set Directory = C:/temp/log4j_output/ for the FileOutput node
+ I set properties for the Log4jLoggingPlugin node as below
![image](https://github.com/ot4i/node-for-log4j/assets/13336339/9f074b22-7d1f-4e08-a513-123a3a734dbf)
+ I create the brokerlog.xml in C:/temp with the content as below
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="trace" monitorInterval="10" strict="false" packages="com.ibm.log4j.filter">
	<Appenders>
		<File name="FILE" fileName="C:/temp/Log4jTest.log" immediateFlush="true" append="true">
			<PatternLayout pattern="%d{yyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
			<ThresholdFilter level="DEBUG"/>
		</File>
	</Appenders>
	<Loggers>
		<Root level="DEBUG">
			<AppenderRef ref="FILE" />
		</Root>
	</Loggers>
</Configuration>
```

=> I build bar file for the TEST FLOW and deploy it to the local ACE server

**TESTING**
+ I put a test file to Input directory C:/temp/log4j_input
+ I see output file in C:/temp/log4j_output/
+ However, log file Log4jTest.log is not created in C:/temp/
+ I manually create the Log4jTest.log in C:/temp/ and test again, but no logs are writing to C:/temp/Log4jTest.log

Could you please help checking my issue and let me know if I miss anything ?

Thank you

Update: I added the link to the source code of my TEST FLOW https://github.com/vietph83/ace-node-for-log4j-demo-issue

**Comment by nieder-github** [comment]
2 things you can try:
1) set logger name to "default" in you node properties
or
2) define a logger "File" in the loggers section of your brokerlog.xml

**Comment by vietph83** [comment]
Hi nieder-github

I do the 2 tests as below

+ The first test:
I set logger name to "default" in the node properties 
![image](https://github.com/ot4i/node-for-log4j/assets/13336339/d25d649e-50cf-4e4b-8abe-61667c8c81cc)
I do not make change to the brokerlog.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="trace" monitorInterval="10" strict="false" packages="com.ibm.log4j.filter">
	<Appenders>
		<File name="FILE" fileName="C:/temp/Log4jTest.log" immediateFlush="true" append="true">
			<PatternLayout pattern="%d{yyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
			<ThresholdFilter level="DEBUG"/>
		</File>
	</Appenders>
	<Loggers>
		<Root level="DEBUG">
			<AppenderRef ref="FILE" />
		</Root>
	</Loggers>
</Configuration>
```
=> I test and no logs are writing to the C:/temp/Log4jTest.log

+ The second test:
I define a logger "File" in loggers section of brokerlog.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="trace" monitorInterval="10" strict="false" packages="com.ibm.log4j.filter">
	<Appenders>
		<File name="FILE" fileName="C:/temp/Log4jTest.log" immediateFlush="true" append="true">
			<PatternLayout pattern="%d{yyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
			<ThresholdFilter level="DEBUG"/>
		</File>
	</Appenders>
	<Loggers>
		<Logger name="File" level="DEBUG">
			<AppenderRef ref="FILE"/>
		</Logger>
		<Root level="DEBUG">
			<AppenderRef ref="FILE" />
		</Root>
	</Loggers>
</Configuration>
```
I do not make any change to the node
![image](https://github.com/ot4i/node-for-log4j/assets/13336339/e40f8a43-fa63-44d2-ad67-0e2f6be713a9)

=> I test and no logs are writing to the C:/temp/Log4jTest.log

Am I missing anything else ?
If possible could you take a look a the source code of my test flow at https://github.com/vietph83/ace-node-for-log4j-demo-issue

Thank you.

**Comment by nieder-github** [comment]
2 more things I'd like you to try:
1) set Log4jConfigFile to "C:\temp\brokerlog.xml"
2) set Log4jConfigFile to "brokerlog.xml" and put the file brokerlog.xml in the classes directory of your installation.

**Comment by vietph83** [comment]
Hi nieder-github

Good news!

1. I try the first thing then test and it still does not work. No log are writing to the C:/temp/Log4jTest.log
2. I try the second thing by copy the brokerlog.xml to C:\Program Files\IBM\ACE\11.0.0.24\server\classes then test it works perfectly

I got the log writing to the C:/temp/Log4jTest.log as below

`2024-01-22 16:46:07.995 [TEST_SERVER_ACE11FP24.TEST_LOG4J] INFO  FILE - My Message is This is a test file for ACE and Log4J`

If I set Logger name = File in brokerlog.xml (not the same as defined in the node) => 1 line of log

```
2024-01-22 16:43:22.653 [TEST_SERVER_ACE11FP24.TEST_LOG4J] INFO  FILE - My Message is This is a test file for ACE and Log4J
2024-01-22 16:43:22.653 [TEST_SERVER_ACE11FP24.TEST_LOG4J] INFO  FILE - My Message is This is a test file for ACE and Log4J

```
If I set Logger name = FILE in brokerlog.xml (same as defined in the node) => 2 lines of log

So the absolute path to the brokerlog.xml set in the node does not work for some reason
or it could be an issue when running on Windows environment. I haven't tried this on linux.

Thank you for helping be debug and figure out the issue so far.
If you have advise / idea for fixing the issue with using absolute path to the brokerlog.xml, that would be great. I really appriciate all your help.

**Comment by nieder-github** [comment]
I will close this and open a new issue for the absolute path on Windows.
Thanks for your testing !! 
PS: Yes, the logger name must be FILE as in the node properties.

**Comment by nieder-github** [comment]
Hi,

may I ask you to send me the stdout and stderr of your server from your first run ( with C:/temp/brokerlog.xml ).

If that is no longer available, may I ask you to repeat the test with your first setup and send me the stdout and stderr ?

Thanks in advance.

**Comment by nieder-github** [comment]
You need to configure the path with leading "/", e.g. /C:/temp/brokerlog.xml.

**Comment by vietph83** [comment]
Hi,
I'm using standalone integrations server in ACE, so all the log (stdout/stderr) should be written to the console.log
To repeat the test, I remove the brokerlog.xml from the C:\Program Files\IBM\ACE\11.0.0.24\server\classes first
Then I put the brokerlog.xml to C:/temp/

I update Log4jConfigFile = C:/temp/brokerlog.xml in the node and test again
No useful info in the console log
```
.....2024-01-23 10:30:02.477918: .2024-01-23 17:30:02.531375: BIP1990I: Integration server 'TEST_SERVER_ACE11FP24' starting initialization; version '11.0.0.24' (64-bit) 
......................Listening for transport dt_socket at address: 9997
....................2024-01-23 17:30:06.782583: BIP2155I: About to 'Initialize' the deployed resource 'TEST_LOG4J' of type 'Application'. 
2024-01-23 17:30:07.098148: BIP2155I: About to 'Start' the deployed resource 'TEST_LOG4J' of type 'Application'. 
2024-01-23 17:30:07.098437: BIP2269I: Deployed resource 'TEST_LOG4J' (uuid='TEST_LOG4J',type='MessageFlow') started successfully. 
..2024-01-23 17:30:07.644109: BIP2866I: IBM App Connect Enterprise administration security is inactive. 
2024-01-23 17:30:07.663700: BIP3132I: The HTTP Listener has started listening on port '7600' for 'RestAdmin http' connections. 
.
2024-01-23 17:30:07.666167: BIP1991I: Integration server has finished initialization. 
2024-01-23 17:37:40.292172: BIP2152I: Configuration message received. 
2024-01-23 17:37:40.375708: BIP2155I: About to 'Stop' the deployed resource 'TEST_LOG4J' of type 'Application'. 
2024-01-23 17:37:44.060172: BIP2271I: Deployed resource 'TEST_LOG4J' (uuid='TEST_LOG4J',type='MessageFlow') successfully stopped. 
2024-01-23 17:37:44.060408: BIP2155I: About to 'TearDown' the deployed resource 'TEST_LOG4J' of type 'Application'. 
2024-01-23 17:37:44.125088: BIP2155I: About to 'Initialize' the deployed resource 'TEST_LOG4J' of type 'Application'. 
2024-01-23 17:37:44.144640: BIP2155I: About to 'Start' the deployed resource 'TEST_LOG4J' of type 'Application'. 
2024-01-23 17:37:44.144940: BIP2269I: Deployed resource 'TEST_LOG4J' (uuid='TEST_LOG4J',type='MessageFlow') started successfully. 
2024-01-23 17:37:44.144988: BIP9332I: Application 'TEST_LOG4J' has been changed successfully. 
2024-01-23 17:37:44.145020: BIP9326I: The source 'TEST_LOG4Jproject.generated.bar' has been successfully deployed. 
2024-01-23 17:37:44.145352: BIP2154I: Integration server finished with Configuration message. 
```
I remember yesterday, the console.log was filled with a lot of useful info when the brokerlog.xml was in the C:\Program Files\IBM\ACE\11.0.0.24\server\classes

Here is the part of the server.conf.yaml of the integration server on my machine related to logging

```
Log:
  consoleLog: true           # Control writing BIP messages to standard out. Set to true or false, default is true.
  outputFormat: 'idText'     # Control the format of BIP messages written to standard out and file. Set to idText, text or ibmjson, default is text if unset.
```

**Comment by vietph83** [comment]
> You need to configure the path with leading "/", e.g. /C:/temp/brokerlog.xml.

I try again as you suggest

I update  Log4jConfigFile = /C:/temp/brokerlog.xml for the node and test again. It works !!!

I got the C:\temp\Log4jTest.log updated with new log

```
2024-01-23 17:49:13.415 [TEST_SERVER_ACE11FP24.TEST_LOG4J] INFO  FILE - My Message is This is a test file for ACE and Log4J
2024-01-23 17:49:13.415 [TEST_SERVER_ACE11FP24.TEST_LOG4J] INFO  FILE - My Message is This is a test file for ACE and Log4J
```

I got the console.log updated as below

```
2024-01-23 17:49:12.962     51 ERROR StatusLogger Invalid URL C:/temp/brokerlog.xml
2024-01-23 17:49:12.963     51  java.net.MalformedURLException: unknown protocol: c
2024-01-23 17:49:12.965     51 	at java.net.URL.<init>(URL.java:629)
2024-01-23 17:49:12.965     51 	at java.net.URL.<init>(URL.java:519)
2024-01-23 17:49:12.966     51 	at java.net.URL.<init>(URL.java:468)
2024-01-23 17:49:12.967     51 	at java.net.URI.toURL(URI.java:1100)
2024-01-23 17:49:12.967     51 	at org.apache.logging.log4j.core.config.ConfigurationSource.fromUri(ConfigurationSource.java:330)
2024-01-23 17:49:12.968     51 	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:505)
2024-01-23 17:49:12.968     51 	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:498)
2024-01-23 17:49:12.969     51 	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:422)
2024-01-23 17:49:12.969     51 	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:323)
2024-01-23 17:49:12.970     51 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:695)
2024-01-23 17:49:12.970     51 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
2024-01-23 17:49:12.971     51 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
2024-01-23 17:49:12.971     51 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
2024-01-23 17:49:12.972     51 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
2024-01-23 17:49:12.972     51 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
2024-01-23 17:49:12.973     51 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
2024-01-23 17:49:12.974     51 	at com.ibm.broker.IAM3.Log4jNode.initLogging(Log4jNode.java:211)
2024-01-23 17:49:12.974     51 	at com.ibm.broker.IAM3.Log4jNode.evaluate(Log4jNode.java:87)
2024-01-23 17:49:12.975     51 	at com.ibm.broker.plugin.MbNode.evaluate(MbNode.java:2138)
2024-01-23 17:49:13.008     51 2024-01-23 17:49:13,007 Thread-22 DEBUG Apache Log4j Core 2.17.1 initializing configuration XmlConfiguration[location=C:\temp\brokerlog.xml]
2024-01-23 17:49:13.012     51 2024-01-23 17:49:13,012 Thread-22 DEBUG Installed 1 script engine
2024-01-23 17:49:13.219     51 2024-01-23 17:49:13,219 Thread-22 DEBUG Oracle Nashorn version: 1.8.0, language: ECMAScript, threading: Not Thread Safe, compile: true, names: [nashorn, Nashorn, js, JS, JavaScript, javascript, ECMAScript, ecmascript], factory class: jdk.nashorn.api.scripting.NashornScriptEngineFactory
2024-01-23 17:49:13.267     51 2024-01-23 17:49:13,267 Thread-22 DEBUG Took 0.045511 seconds to load 0 plugins from package com.ibm.log4j.filter
2024-01-23 17:49:13.268     51 2024-01-23 17:49:13,267 Thread-22 DEBUG PluginManager 'Core' found 128 plugins
2024-01-23 17:49:13.269     51 2024-01-23 17:49:13,268 Thread-22 DEBUG PluginManager 'Level' found 0 plugins
2024-01-23 17:49:13.275     51 2024-01-23 17:49:13,275 Thread-22 DEBUG PluginManager 'Lookup' found 16 plugins
2024-01-23 17:49:13.278     51 2024-01-23 17:49:13,278 Thread-22 DEBUG Building Plugin[name=layout, class=org.apache.logging.log4j.core.layout.PatternLayout].
2024-01-23 17:49:13.290     51 2024-01-23 17:49:13,290 Thread-22 TRACE TypeConverterRegistry initializing.
2024-01-23 17:49:13.291     51 2024-01-23 17:49:13,291 Thread-22 DEBUG PluginManager 'TypeConverter' found 26 plugins
2024-01-23 17:49:13.305     51 2024-01-23 17:49:13,305 Thread-22 DEBUG PatternLayout$Builder(pattern="%d{yyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n", PatternSelector=null, Configuration(C:\temp\brokerlog.xml), Replace=null, charset="null", alwaysWriteExceptions="null", disableAnsi="null", noConsoleNoAnsi="null", header="null", footer="null")
2024-01-23 17:49:13.307     51 2024-01-23 17:49:13,306 Thread-22 DEBUG PluginManager 'Converter' found 45 plugins
2024-01-23 17:49:13.321     51 2024-01-23 17:49:13,321 Thread-22 DEBUG Building Plugin[name=filter, class=org.apache.logging.log4j.core.filter.ThresholdFilter].
2024-01-23 17:49:13.330     51 2024-01-23 17:49:13,330 Thread-22 DEBUG createFilter(level="DEBUG", onMatch="null", onMismatch="null")
2024-01-23 17:49:13.331     51 2024-01-23 17:49:13,331 Thread-22 DEBUG Building Plugin[name=appender, class=org.apache.logging.log4j.core.appender.FileAppender].
2024-01-23 17:49:13.343     51 2024-01-23 17:49:13,343 Thread-22 DEBUG FileAppender$Builder(fileName="C:/temp/Log4jTest.log", append="true", locking="null", advertise="null", advertiseUri="null", createOnDemand="null", filePermissions="null", fileOwner="null", fileGroup="null", bufferedIo="null", bufferSize="null", immediateFlush="true", ignoreExceptions="null", PatternLayout(%d{yyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n), name="FILE", Configuration(C:\temp\brokerlog.xml), ThresholdFilter(DEBUG), ={})
2024-01-23 17:49:13.351     51 2024-01-23 17:49:13,351 Thread-22 DEBUG Starting FileManager C:/temp/Log4jTest.log
2024-01-23 17:49:13.353     51 2024-01-23 17:49:13,352 Thread-22 DEBUG Building Plugin[name=appenders, class=org.apache.logging.log4j.core.config.AppendersPlugin].
2024-01-23 17:49:13.354     51 2024-01-23 17:49:13,354 Thread-22 DEBUG createAppenders(={FILE})
2024-01-23 17:49:13.355     51 2024-01-23 17:49:13,355 Thread-22 DEBUG Building Plugin[name=AppenderRef, class=org.apache.logging.log4j.core.config.AppenderRef].
2024-01-23 17:49:13.357     51 2024-01-23 17:49:13,357 Thread-22 DEBUG createAppenderRef(ref="FILE", level="null", Filter=null)
2024-01-23 17:49:13.358     51 2024-01-23 17:49:13,358 Thread-22 DEBUG Building Plugin[name=logger, class=org.apache.logging.log4j.core.config.LoggerConfig].
2024-01-23 17:49:13.361     51 2024-01-23 17:49:13,361 Thread-22 DEBUG createLogger(additivity="true", level="DEBUG", name="FILE", includeLocation="null", ={FILE}, ={}, Configuration(C:\temp\brokerlog.xml), Filter=null)
2024-01-23 17:49:13.363     51 2024-01-23 17:49:13,362 Thread-22 DEBUG Building Plugin[name=AppenderRef, class=org.apache.logging.log4j.core.config.AppenderRef].
2024-01-23 17:49:13.364     51 2024-01-23 17:49:13,363 Thread-22 DEBUG createAppenderRef(ref="FILE", level="null", Filter=null)
2024-01-23 17:49:13.364     51 2024-01-23 17:49:13,364 Thread-22 DEBUG Building Plugin[name=root, class=org.apache.logging.log4j.core.config.LoggerConfig$RootLogger].
2024-01-23 17:49:13.365     51 2024-01-23 17:49:13,365 Thread-22 DEBUG createLogger(additivity="null", level="DEBUG", includeLocation="null", ={FILE}, ={}, Configuration(C:\temp\brokerlog.xml), Filter=null)
2024-01-23 17:49:13.367     51 2024-01-23 17:49:13,366 Thread-22 DEBUG Building Plugin[name=loggers, class=org.apache.logging.log4j.core.config.LoggersPlugin].
2024-01-23 17:49:13.368     51 2024-01-23 17:49:13,368 Thread-22 DEBUG createLoggers(={FILE, root})
2024-01-23 17:49:13.370     51 2024-01-23 17:49:13,370 Thread-22 DEBUG Configuration XmlConfiguration[location=C:\temp\brokerlog.xml] initialized
2024-01-23 17:49:13.370     51 2024-01-23 17:49:13,370 Thread-22 DEBUG Starting configuration XmlConfiguration[location=C:\temp\brokerlog.xml]
2024-01-23 17:49:13.371     51 2024-01-23 17:49:13,371 Thread-22 DEBUG Log4j2 ConfigurationScheduler starting 1 threads
2024-01-23 17:49:13.374     51 2024-01-23 17:49:13,373 Thread-22 DEBUG Started configuration XmlConfiguration[location=C:\temp\brokerlog.xml] OK.
2024-01-23 17:49:13.374     51 2024-01-23 17:49:13,374 Thread-22 TRACE Stopping org.apache.logging.log4j.core.config.DefaultConfiguration@1243ed6e...
2024-01-23 17:49:13.375     51 2024-01-23 17:49:13,375 Thread-22 TRACE DefaultConfiguration notified 1 ReliabilityStrategies that config will be stopped.
2024-01-23 17:49:13.376     51 2024-01-23 17:49:13,376 Thread-22 TRACE DefaultConfiguration stopping root LoggerConfig.
2024-01-23 17:49:13.376     51 2024-01-23 17:49:13,376 Thread-22 TRACE DefaultConfiguration notifying ReliabilityStrategies that appenders will be stopped.
2024-01-23 17:49:13.377     51 2024-01-23 17:49:13,377 Thread-22 TRACE DefaultConfiguration stopping remaining Appenders.
2024-01-23 17:49:13.378     51 2024-01-23 17:49:13,377 Thread-22 DEBUG Shutting down OutputStreamManager SYSTEM_OUT.false.false-1
2024-01-23 17:49:13.378     51 2024-01-23 17:49:13,378 Thread-22 DEBUG OutputStream closed
2024-01-23 17:49:13.379     51 2024-01-23 17:49:13,379 Thread-22 DEBUG Shut down OutputStreamManager SYSTEM_OUT.false.false-1, all resources released: true
2024-01-23 17:49:13.379     51 2024-01-23 17:49:13,379 Thread-22 DEBUG Appender DefaultConsole-1 stopped with status true
2024-01-23 17:49:13.380     51 2024-01-23 17:49:13,380 Thread-22 TRACE DefaultConfiguration stopped 1 remaining Appenders.
2024-01-23 17:49:13.380     51 2024-01-23 17:49:13,380 Thread-22 TRACE DefaultConfiguration cleaning Appenders from 1 LoggerConfigs.
2024-01-23 17:49:13.381     51 2024-01-23 17:49:13,381 Thread-22 DEBUG Stopped org.apache.logging.log4j.core.config.DefaultConfiguration@1243ed6e OK
2024-01-23 17:49:13.383     51 2024-01-23 17:49:13,383 Thread-22 TRACE Reregistering MBeans after reconfigure. Selector=org.apache.logging.log4j.core.selector.ClassLoaderContextSelector@3e0b87ba
2024-01-23 17:49:13.383     51 2024-01-23 17:49:13,383 Thread-22 TRACE Reregistering context (1/1): '53fbac2f' org.apache.logging.log4j.core.LoggerContext@aab1935d
2024-01-23 17:49:13.384     51 2024-01-23 17:49:13,384 Thread-22 TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=53fbac2f'
2024-01-23 17:49:13.385     51 2024-01-23 17:49:13,385 Thread-22 TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=53fbac2f,component=StatusLogger'
2024-01-23 17:49:13.385     51 2024-01-23 17:49:13,385 Thread-22 TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=53fbac2f,component=ContextSelector'
2024-01-23 17:49:13.386     51 2024-01-23 17:49:13,386 Thread-22 TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=53fbac2f,component=Loggers,name=*'
2024-01-23 17:49:13.387     51 2024-01-23 17:49:13,386 Thread-22 TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=53fbac2f,component=Appenders,name=*'
2024-01-23 17:49:13.387     51 2024-01-23 17:49:13,387 Thread-22 TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=53fbac2f,component=AsyncAppenders,name=*'
2024-01-23 17:49:13.387     51 2024-01-23 17:49:13,387 Thread-22 TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=53fbac2f,component=AsyncLoggerRingBuffer'
2024-01-23 17:49:13.388     51 2024-01-23 17:49:13,388 Thread-22 TRACE Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=53fbac2f,component=Loggers,name=*,subtype=RingBuffer'
2024-01-23 17:49:13.390     51 2024-01-23 17:49:13,390 Thread-22 DEBUG Registering MBean org.apache.logging.log4j2:type=53fbac2f
2024-01-23 17:49:13.392     51 2024-01-23 17:49:13,392 Thread-22 DEBUG Registering MBean org.apache.logging.log4j2:type=53fbac2f,component=StatusLogger
2024-01-23 17:49:13.394     51 2024-01-23 17:49:13,393 Thread-22 DEBUG Registering MBean org.apache.logging.log4j2:type=53fbac2f,component=ContextSelector
2024-01-23 17:49:13.395     51 2024-01-23 17:49:13,395 Thread-22 DEBUG Registering MBean org.apache.logging.log4j2:type=53fbac2f,component=Loggers,name=
2024-01-23 17:49:13.396     51 2024-01-23 17:49:13,396 Thread-22 DEBUG Registering MBean org.apache.logging.log4j2:type=53fbac2f,component=Loggers,name=FILE
2024-01-23 17:49:13.397     51 2024-01-23 17:49:13,397 Thread-22 DEBUG Registering MBean org.apache.logging.log4j2:type=53fbac2f,component=Appenders,name=FILE
2024-01-23 17:49:13.399     51 2024-01-23 17:49:13,399 Thread-22 TRACE Using default SystemClock for timestamps.
2024-01-23 17:49:13.399     51 2024-01-23 17:49:13,399 Thread-22 DEBUG org.apache.logging.log4j.core.util.SystemClock does not support precise timestamps.
2024-01-23 17:49:13.400     51 2024-01-23 17:49:13,400 Thread-22 TRACE Using DummyNanoClock for nanosecond timestamps.
2024-01-23 17:49:13.401     51 2024-01-23 17:49:13,401 Thread-22 DEBUG Reconfiguration complete for context[name=53fbac2f] at URI C:\temp\brokerlog.xml (org.apache.logging.log4j.core.LoggerContext@aab1935d) with optional ClassLoader: null
2024-01-23 17:49:13.402     51 2024-01-23 17:49:13,402 Thread-22 DEBUG Shutdown hook enabled. Registering a new one.
2024-01-23 17:49:13.404     51 2024-01-23 17:49:13,403 Thread-22 DEBUG LoggerContext[name=53fbac2f, org.apache.logging.log4j.core.LoggerContext@aab1935d] started OK.
2024-01-23 17:49:23.383     55 2024-01-23 17:49:23,381 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:49:23.386     55 2024-01-23 17:49:23,386 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:49:33.395     55 2024-01-23 17:49:33,395 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:49:33.397     55 2024-01-23 17:49:33,396 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:49:43.403     55 2024-01-23 17:49:43,403 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:49:43.404     55 2024-01-23 17:49:43,404 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:49:53.415     55 2024-01-23 17:49:53,414 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:49:53.417     55 2024-01-23 17:49:53,416 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:50:03.430     55 2024-01-23 17:50:03,429 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:50:03.432     55 2024-01-23 17:50:03,431 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:50:13.435     55 2024-01-23 17:50:13,434 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:50:13.437     55 2024-01-23 17:50:13,436 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:50:23.443     55 2024-01-23 17:50:23,443 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:50:23.446     55 2024-01-23 17:50:23,446 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:50:33.461     55 2024-01-23 17:50:33,461 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:50:33.463     55 2024-01-23 17:50:33,463 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:50:43.469     55 2024-01-23 17:50:43,468 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:50:43.471     55 2024-01-23 17:50:43,471 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:50:53.479     55 2024-01-23 17:50:53,478 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:50:53.481     55 2024-01-23 17:50:53,480 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:51:03.495     55 2024-01-23 17:51:03,494 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:51:03.496     55 2024-01-23 17:51:03,496 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:51:13.511     55 2024-01-23 17:51:13,511 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:51:13.513     55 2024-01-23 17:51:13,513 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:51:23.518     55 2024-01-23 17:51:23,517 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:51:23.519     55 2024-01-23 17:51:23,519 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:51:33.533     55 2024-01-23 17:51:33,533 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:51:33.534     55 2024-01-23 17:51:33,534 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:51:43.545     55 2024-01-23 17:51:43,544 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:51:43.546     55 2024-01-23 17:51:43,546 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.
2024-01-23 17:51:53.562     55 2024-01-23 17:51:53,562 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run triggered.
2024-01-23 17:51:53.565     55 2024-01-23 17:51:53,564 Log4j2-TF-2-Scheduled-1 TRACE WatchRunnable run ended.

```
